[package]
name = "jobs_scheduler_client"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
crossterm = "0.27.0"
ratatui = { version = "0.22.0", features = ["all-widgets"] }
regex = "1.9.3"
chrono = "0.4.26"
directories = "5.0"
